name: Vijay Lab
description: Virus evolution epidemiology and phylodynamics
url: http://vjlab.io

markdown: redcarpet
permalink: /:categories/:title/
future: true

redcarpet:
  extensions:
   - tables
   - no_intra_emphasis
   - autolink
   - superscript
   - strikethrough

exclude:
  - "*.branches"
  - "*.kml"
  - "*.log"
  - "*.nb"
  - "*.trees"
  - "*.cpp"
  - "*.h"
  - "*.hh"
  - "*.java"
  - "*.jar"
  - "*.csv"
  - "*.tsv"
  - "*.txt"
  - "*.rb"
  - "*.py"
  - "*.class"
  - "*.tips"
  - "*.fasta"
  - "*.nex"
  - "Gemfile"
  - "Gemfile.lock"
  - "s3_website.yml"

projects:
  - vdha/bms5003-week3
  - Don86/mic-scrapbook
