name: Pathogen Evolution Lab
description: Virus evolution epidemiology and phylodynamics
url: http://vjlab.io

markdown: kramdown
permalink: /:categories/:title/
future: true
sass:
    sass_dir: css
    
plugins: ['jekyll-twitter-plugin']


exclude:
  - "*.branches"
  - "*.kml"
  - "*.log"
  - "*.nb"
  - "*.trees"
  - "*.cpp"
  - "*.h"
  - "*.hh"
  - "*.java"
  - "*.jar"
  - "*.csv"
  - "*.tsv"
  - "*.txt"
  - "*.rb"
  - "*.py"
  - "*.class"
  - "*.tips"
  - "*.fasta"
  - "*.nex"
  - "Gemfile"
  - "Gemfile.lock"
  - "s3_website.yml"

projects:
#  - vdha/bms5003-week3
#  - Don86/mic-scrapbook
  - vjlab/resources
